Building with forms
Zubenna/rails-forms pull request #2
Opened 2020-08-04 22:11 UTC by AdfPizarro

Setup the DB and migration for the users
Included form to create and edit user

Add validators on the server-side
Display red color on the fields with validation errors

2020-08-07 00:55 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello 
Thank you for the job done so far.
However there are some changes to do. Read them in the comments below.

Once the code updated, kindly submit a new code review request. 

Thanks
Mael FOSSO

2020-08-07 00:55 UTC, maelfosso commented on app/controllers/users_controller.rb
> +    @user = User.new(email: 'example@example.com')
Please, move `example@example.com` in the placeholder of the form

2020-08-07 00:55 UTC, maelfosso commented on app/controllers/users_controller.rb
> +  end
It's not working sorry.

2020-08-07 00:55 UTC, maelfosso commented on app/controllers/users_controller.rb
> +    # @user = User.new(whitelisted_user_params)
Remove comments

2020-08-07 00:55 UTC, maelfosso commented on config/routes.rb
> +  resources :users, only: %i[create new edit index update]
As indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route1.png), the routes are restricted.

2020-08-07 00:55 UTC, maelfosso commented on app/views/users/new.html.erb
> + <% end %> -->
The first form implementation is not conform to the requirements.
Take a look of the requirements [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png)

2020-08-07 00:55 UTC, maelfosso commented on app/views/users/new.html.erb
> +     <% end %>
Even it's a good idea, the implementation is not good. 
You must avoid logic in views. Please, use instead view helpers for that.

2020-08-07 15:14 UTC, AdfPizarro commented on app/controllers/users_controller.rb
> +    # @user = User.new(whitelisted_user_params)
Line removed

2020-08-07 15:16 UTC, AdfPizarro commented on app/controllers/users_controller.rb
> +    @user = User.new(email: 'example@example.com')
Moved to the view

2020-08-07 15:40 UTC, AdfPizarro commented on app/controllers/users_controller.rb
> +  end
Created view to list all the users and links to edit each one

2020-08-07 15:41 UTC, AdfPizarro commented on config/routes.rb
> +  resources :users, only: %i[create new edit index update]
We nee the routes in order to be able to update and list users, this instruction doesn't make sense

2020-08-07 15:56 UTC, AdfPizarro commented on app/views/users/new.html.erb
> + <% end %> -->
Added the original form in plain html, modified to send and object instead

2020-08-07 16:04 UTC, AdfPizarro commented on app/views/users/new.html.erb
> +     <% end %>
Removed unnecessary logic from the views added method to list errors

2020-08-08 16:47 UTC, jofer86 approved these changes
## :wave: :wave: Hello! I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- All of the required changes were met, well done!! This project is vanquished!!
## `const PROJECT_STATUS = 'Approved'` 🚀 🚀 🚀
--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-08-10 15:01 UTC, merged